blank_issues_enabled: false

contact_links:
  - name: 📚 Quickstart & Docs
    url: https://bigmangotree.github.io/docs/Quickstart.html
    about: Read Quickstart and Troubleshooting before filing an issue.

  - name: 🧾 Troubleshooting
    url: https://bigmangotree.github.io/docs/Troubleshooting.html
    about: Common errors and their fixes.

  - name: ✉️ Email Support (fallback)
    url: mailto:support@bigmangotree.com
    about: Use only if you cannot submit a GitHub Issue.

# Default settings for issue templates
# This ensures issues assign to you (or your team) → triggers email notifications
default:
  assignees:
    - bobohan777   # 👈 replace with your GitHub handle
    - Polymer265
    - sithuhlaing
  labels:
    - support
