name: Test Email Send

on:
  workflow_dispatch:   # Manual trigger

jobs:
  test-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Test Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "GitHub Test Email"
          body: "This is a test email from GitHub Actions."
          to: bigmangotree777@gmail.com
          from: GitHub Issue Bot <bigmangotree777@gmail.com>
