name: Issue Notifications

on:
  # Manual test button in the Actions tab
  workflow_dispatch:
  # Fire when a new issue is opened
  issues:
    types: [opened]
  # Fire when a new comment is added to any issue
  issue_comment:
    types: [created]

jobs:
  email-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email (new issue or comment)
        uses: dawidd6/action-send-mail@v3
        with:
          # Gmail SMTP
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}

          subject: >
            [${{ github.repository }}] Issue update: ${{ github.event.issue.title }}

          body: |
            Repository: ${{ github.repository }}
            Action: ${{ github.event.action }}
            Actor: ${{ github.event.sender.login }}

            Issue: #${{ github.event.issue.number }} — ${{ github.event.issue.title }}
            Link:  ${{ github.event.issue.html_url }}

            --------
            ${{ github.event.comment.body || 'New issue opened.' }}

          to: ${{ secrets.TO_EMAIL }}
          from: GitHub Issue Bot <${{ secrets.SMTP_USERNAME }}>
